### ISSUE TITLE
Check risk calculation feature in case "splits" are used - these splits should not count into risk score

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#142]
![image](https://user-images.githubusercontent.com/23223285/189591499-8da1eec1-7e5a-4167-9878-53c254f81052.png)

**Comment by qngngyn** [comment]
Fix with 26feaeea89c2c99ea9c0c4c394bae37ec4019c4e
Now asks for Hyper-V in both benchmarks. Also in Windows 10 and Windows 11.

Also fixed with fbf11b1de92aef9640221436e288a3024272828d
Following IDs were also changed: "2.2.29 A", "2.2.29 B", "2.2.18-2", "2.2.18_2", "2.2.18.2", "2.2.18 A", "2.2.18 B",
