### ISSUE TITLE
Server 2019 Report

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#176]
1. Legal Notice Message (CIS 2.3.7.4) is compliant even though not set.
Please check. Somehow Checks for 2.3.7.4 and 2.3.7.5 differ when looking at their logic. Also in case of fail, please change output to "Interactive logon: Message text not set" and "Interactive logon: Message title not set"

Please also check this for other auditgroups

**Comment by qngngyn** [comment]
For odd reasons this behaviour has been replicated on a fresh Server 2019 installation. 
Even though the String is empty, it still shows compliant. 

This changes when the input is set by hand, and removed again. - Not compliant.
Also when the Key is being removed and newly added, the output is correct - Not compliant.

Issue seems to arise since on fresh installation the legalnoticetext seems to have an invisible character. 
![grafik](https://user-images.githubusercontent.com/104337428/207332293-23baec61-462f-495c-9a11-e09dcda99104.png)

**Comment by qngngyn** [comment]
Fixed by asking whether the length is 1 or not (special rule only for this weird case).
