### ISSUE TITLE
Same (?) Rule seems to lead to different results in same report  

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#191]
Compliance here: 
![image](https://user-images.githubusercontent.com/23223285/207963844-2b53a7d5-5027-41fa-9193-1dfc7121c363.png)

Non compliance here:
![image](https://user-images.githubusercontent.com/23223285/207963893-a7a682fc-5596-409d-bf07-f60e21944bc8.png)

**Comment by SteffenWinternheimer** [comment]
In fact, there are different from each other. Each rule checks for another path.
I updated all Task Titles in every AuditGroup relating to this problem in order to make the difference clearer. 

![grafik](https://user-images.githubusercontent.com/35689334/208398932-ae4f4cd4-fe93-449b-8a0f-cfc6249178d5.png)
![grafik](https://user-images.githubusercontent.com/35689334/208398989-e9ccc220-ccee-4024-aad8-70863ebc096c.png)
