### ISSUE TITLE
AUDIT Windows 10

### ISSUE THREAD

**Issue by andrelindenfb** [fbprogmbh/Audit-Test-Automation#51]
Hello,

Error feedback within the audit TAP 4.5

None:
17.3.1 - Cannot get Subcategory ''
17.5.2 - Cannot get Subcategory ''
17.5.5 - Cannot get Subcategory 'Other Logon Logoff Events'
17.7.4 - Cannot get Subcategory 'Mpssvc Rule Level Policy Change'

False:
1.2.2 - 'LockoutBadCount' currently set to: 3. Expected: x <= 10 and x > 0
2.2.14 - The user right 'SeCreateSymbolicLinkPrivilege' contains following unexpected users: NT VIRTUAL MACHINE\Virtual Machines

Best
Andre

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/942664317a3ea8b67d13ff471a0194b7ab751726 
{
None:
17.3.1 - Cannot get Subcategory ''
17.5.2 - Cannot get Subcategory ''
17.5.5 - Cannot get Subcategory 'Other Logon Logoff Events'
17.7.4 - Cannot get Subcategory 'Mpssvc Rule Level Policy Change'
}

Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/17c6b0d1858943e4b73caa455ed78b410ac4a03b
{
False:
1.2.2 - 'LockoutBadCount' currently set to: 3. Expected: x <= 10 and x > 0
}

Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/aa723f166bdecc2434f225ed93e3ca10157ef0d0
{
False:
2.2.14 - The user right 'SeCreateSymbolicLinkPrivilege' contains following unexpected users: NT VIRTUAL MACHINE\Virtual Machines
}
